# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviousSearches',
            new_name='PreviousSearch',
        ),
    ]
