# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0003_auto_20170721_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.RenameModel(
            old_name='UserSearches',
            new_name='UserSearch',
        ),
    ]
