# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0004_auto_20170721_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='places',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='places',
        ),
        migrations.AddField(
            model_name='favorite',
            name='place',
            field=models.ManyToManyField(to='foursquaresearch.Place'),
        ),
        migrations.DeleteModel(
            name='UserSearch',
        ),
    ]
