# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0008_auto_20170724_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSearch',
        ),
    ]
