# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0010_usersearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearch',
            old_name='place',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='usersearch',
            old_name='user',
            new_name='username',
        ),
    ]
