# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0011_auto_20170725_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='search',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='username',
        ),
        migrations.DeleteModel(
            name='UserSearch',
        ),
    ]
