# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foursquaresearch', '0012_auto_20170725_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.ManyToManyField(to='foursquaresearch.PreviousSearch')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
