# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0015_auto_20170725_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='place',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
