# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0019_usersearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='search',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
        migrations.DeleteModel(
            name='PreviousSearch',
        ),
        migrations.DeleteModel(
            name='UserSearch',
        ),
    ]
