# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foursquaresearch', '0021_previoussearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='foursquare_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('user', 'place')]),
        ),
    ]
