# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquaresearch', '0022_auto_20170731_1522'),
        ('foursquaresearch', '0022_auto_20170804_1303'),
    ]

    operations = [
    ]
