# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170808_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
